// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: novoPojeto

#include "ui.h"
#include "display/local_fonts.h"




lv_obj_t *ui_Screen1 = NULL;lv_obj_t *ui_Panel1 = NULL;lv_obj_t *ui_Panel2 = NULL;lv_obj_t *ui_Panel3 = NULL;lv_obj_t *ui_Label1 = NULL;lv_obj_t *ui_clock = NULL;lv_obj_t *ui_Label3 = NULL;lv_obj_t *ui_Bar1 = NULL;lv_obj_t *ui_Bar2 = NULL;lv_obj_t *ui_Panel4 = NULL;lv_obj_t *ui_Panel5 = NULL;lv_obj_t *ui_Label4 = NULL;lv_obj_t *ui_Label5 = NULL;lv_obj_t *ui_Label2 = NULL;lv_obj_t *ui_Label6 = NULL;lv_obj_t *ui_khMin = NULL;lv_obj_t *ui_khMax = NULL;lv_obj_t *ui_dhkValue = NULL;lv_obj_t *ui_KhminDay = NULL;lv_obj_t *ui_KhmaxDay = NULL;lv_obj_t *ui_KhVarDay = NULL;
lv_obj_t *ui_loading = NULL;
lv_obj_t *ui_status = NULL;

// event funtions


// build funtions

void ui_Screen1_screen_init(void)
{
ui_Screen1 = lv_obj_create(NULL);
lv_obj_clear_flag( ui_Screen1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Panel1 = lv_obj_create(ui_Screen1);
lv_obj_set_width( ui_Panel1, 312);
lv_obj_set_height( ui_Panel1, 28);
lv_obj_set_x( ui_Panel1, 0 );
lv_obj_set_y( ui_Panel1, -68 );
lv_obj_set_align( ui_Panel1, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Panel1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Panel2 = lv_obj_create(ui_Screen1);
lv_obj_set_width( ui_Panel2, 154);
lv_obj_set_height( ui_Panel2, 132);
lv_obj_set_x( ui_Panel2, 4 );
lv_obj_set_y( ui_Panel2, 16 );
lv_obj_set_align( ui_Panel2, LV_ALIGN_LEFT_MID );
lv_obj_clear_flag( ui_Panel2, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Panel3 = lv_obj_create(ui_Screen1);
lv_obj_set_width( ui_Panel3, 154);
lv_obj_set_height( ui_Panel3, 132);
lv_obj_set_x( ui_Panel3, 162 );
lv_obj_set_y( ui_Panel3, 16 );
lv_obj_set_align( ui_Panel3, LV_ALIGN_LEFT_MID );
lv_obj_clear_flag( ui_Panel3, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Label1 = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_Label1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label1, -93 );
lv_obj_set_y( ui_Label1, -69 );
lv_obj_set_align( ui_Label1, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label1,"ReefBlueSky KH");

ui_clock = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_clock, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_clock, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_clock, 119 );
lv_obj_set_y( ui_clock, -68 );
lv_obj_set_align( ui_clock, LV_ALIGN_CENTER );
lv_label_set_text(ui_clock,"12:00");

ui_Label3 = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_Label3, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label3, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label3, -80 );
lv_obj_set_y( ui_Label3, -32 );
lv_obj_set_align( ui_Label3, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label3,"dKH");

ui_Bar1 = lv_bar_create(ui_Screen1);
lv_bar_set_value(ui_Bar1,25,LV_ANIM_OFF);
lv_bar_set_start_value(ui_Bar1, 0, LV_ANIM_OFF);
lv_obj_set_width( ui_Bar1, 127);
lv_obj_set_height( ui_Bar1, 10);
lv_obj_set_x( ui_Bar1, -80 );
lv_obj_set_y( ui_Bar1, 60 );
lv_obj_set_align( ui_Bar1, LV_ALIGN_CENTER );

ui_Bar2 = lv_bar_create(ui_Screen1);
lv_bar_set_value(ui_Bar2,25,LV_ANIM_OFF);
lv_bar_set_start_value(ui_Bar2, 0, LV_ANIM_OFF);
lv_obj_set_width( ui_Bar2, 127);
lv_obj_set_height( ui_Bar2, 10);
lv_obj_set_x( ui_Bar2, 77 );
lv_obj_set_y( ui_Bar2, 67 );
lv_obj_set_align( ui_Bar2, LV_ALIGN_CENTER );

ui_Panel4 = lv_obj_create(ui_Screen1);
lv_obj_set_width( ui_Panel4, 141);
lv_obj_set_height( ui_Panel4, 48);
lv_obj_set_x( ui_Panel4, 167 );
lv_obj_set_y( ui_Panel4, -4 );
lv_obj_set_align( ui_Panel4, LV_ALIGN_LEFT_MID );
lv_obj_clear_flag( ui_Panel4, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Panel5 = lv_obj_create(ui_Screen1);
lv_obj_set_width( ui_Panel5, 141);
lv_obj_set_height( ui_Panel5, 31);
lv_obj_set_x( ui_Panel5, 168 );
lv_obj_set_y( ui_Panel5, 40 );
lv_obj_set_align( ui_Panel5, LV_ALIGN_LEFT_MID );
lv_obj_clear_flag( ui_Panel5, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Label4 = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_Label4, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label4, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label4, 76 );
lv_obj_set_y( ui_Label4, -40 );
lv_obj_set_align( ui_Label4, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label4,"Detalhes");

ui_Label5 = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_Label5, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label5, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label5, 31 );
lv_obj_set_y( ui_Label5, -14 );
lv_obj_set_align( ui_Label5, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label5,"MIN:");

ui_Label2 = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_Label2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label2, 31 );
lv_obj_set_y( ui_Label2, 4 );
lv_obj_set_align( ui_Label2, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label2,"MAX:");

ui_Label6 = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_Label6, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label6, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label6, 31 );
lv_obj_set_y( ui_Label6, 40 );
lv_obj_set_align( ui_Label6, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label6,"VAR:");

ui_khMin = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_khMin, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_khMin, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_khMin, -142 );
lv_obj_set_y( ui_khMin, 72 );
lv_obj_set_align( ui_khMin, LV_ALIGN_CENTER );
lv_label_set_text(ui_khMin,"0");

ui_khMax = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_khMax, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_khMax, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_khMax, -17 );
lv_obj_set_y( ui_khMax, 72 );
lv_obj_set_align( ui_khMax, LV_ALIGN_CENTER );
lv_label_set_text(ui_khMax,"0");

ui_dhkValue = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_dhkValue, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_dhkValue, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_dhkValue, -77 );
lv_obj_set_y( ui_dhkValue, 11 );
lv_obj_set_align( ui_dhkValue, LV_ALIGN_CENTER );
lv_label_set_text(ui_dhkValue,"0,00");
lv_obj_set_style_text_font(ui_dhkValue, get_montserrat_bold_32(), LV_PART_MAIN | LV_STATE_DEFAULT);

ui_KhminDay = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_KhminDay, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_KhminDay, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_KhminDay, 87 );
lv_obj_set_y( ui_KhminDay, -14 );
lv_obj_set_align( ui_KhminDay, LV_ALIGN_CENTER );
lv_label_set_text(ui_KhminDay,"0,00");

ui_KhmaxDay = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_KhmaxDay, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_KhmaxDay, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_KhmaxDay, 87 );
lv_obj_set_y( ui_KhmaxDay, 4 );
lv_obj_set_align( ui_KhmaxDay, LV_ALIGN_CENTER );
lv_label_set_text(ui_KhmaxDay,"0,00");

ui_KhVarDay = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_KhVarDay, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_KhVarDay, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_KhVarDay, 89 );
lv_obj_set_y( ui_KhVarDay, 40 );
lv_obj_set_align( ui_KhVarDay, LV_ALIGN_CENTER );
lv_label_set_text(ui_KhVarDay,"0,00");

ui_loading = lv_spinner_create(ui_Screen1,1000,90);
lv_obj_set_width( ui_loading, 16);
lv_obj_set_height( ui_loading, 12);
lv_obj_set_x( ui_loading, -12 );
lv_obj_set_y( ui_loading, -69 );
lv_obj_set_align( ui_loading, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_loading, LV_OBJ_FLAG_CLICKABLE );    /// Flags
lv_obj_add_flag( ui_loading, LV_OBJ_FLAG_HIDDEN );


ui_status = lv_label_create(ui_Screen1);
lv_label_set_text(ui_status,"");
lv_obj_set_width( ui_status, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_status, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_status, 46 );
lv_obj_set_y( ui_status, -68 );
lv_obj_set_align( ui_status, LV_ALIGN_CENTER );

}

void ui_Screen1_screen_destroy(void)
{
   if (ui_Screen1) lv_obj_del(ui_Screen1);

// NULL screen variables
ui_Screen1= NULL;
ui_Panel1= NULL;
ui_Panel2= NULL;
ui_Panel3= NULL;
ui_Label1= NULL;
ui_clock= NULL;
ui_Label3= NULL;
ui_Bar1= NULL;
ui_Bar2= NULL;
ui_Panel4= NULL;
ui_Panel5= NULL;
ui_Label4= NULL;
ui_Label5= NULL;
ui_Label2= NULL;
ui_Label6= NULL;
ui_khMin= NULL;
ui_khMax= NULL;
ui_dhkValue= NULL;
ui_KhminDay= NULL;
ui_KhmaxDay= NULL;
ui_KhVarDay= NULL;
ui_loading= NULL;
ui_status= NULL;

}
