// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: novoPojeto

#ifndef UI_SCREEN1_H
#define UI_SCREEN1_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen1
extern void ui_Screen1_screen_init(void);
extern void ui_Screen1_screen_destroy(void);
extern lv_obj_t *ui_Screen1;
extern lv_obj_t *ui_Panel1;
extern lv_obj_t *ui_Panel2;
extern lv_obj_t *ui_Panel3;
extern lv_obj_t *ui_Label1;
extern lv_obj_t *ui_clock;
extern lv_obj_t *ui_Label3;
extern lv_obj_t *ui_Bar1;
extern lv_obj_t *ui_Bar2;
extern lv_obj_t *ui_Panel4;
extern lv_obj_t *ui_Panel5;
extern lv_obj_t *ui_Label4;
extern lv_obj_t *ui_Label5;
extern lv_obj_t *ui_Label2;
extern lv_obj_t *ui_Label6;
extern lv_obj_t *ui_khMin;
extern lv_obj_t *ui_khMax;
extern lv_obj_t *ui_dhkValue;
extern lv_obj_t *ui_KhminDay;
extern lv_obj_t *ui_KhmaxDay;
extern lv_obj_t *ui_KhVarDay;
extern lv_obj_t *ui_loading;
extern lv_obj_t *ui_status;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

