// idf_compat.h
#pragma once

#ifndef CONFIG_IDF_TARGET_ESP32
#define CONFIG_IDF_TARGET_ESP32 0
#endif

#ifndef CONFIG_IDF_TARGET_ESP32S2
#define CONFIG_IDF_TARGET_ESP32S2 0
#endif

#ifndef CONFIG_IDF_TARGET_ESP32S3
#define CONFIG_IDF_TARGET_ESP32S3 0
#endif

#ifndef CONFIG_IDF_TARGET_ESP32C2
#define CONFIG_IDF_TARGET_ESP32C2 0
#endif

#ifndef CONFIG_IDF_TARGET_ESP32C3
#define CONFIG_IDF_TARGET_ESP32C3 0
#endif

#ifndef CONFIG_IDF_TARGET_ESP32C6
#define CONFIG_IDF_TARGET_ESP32C6 1
#endif
