// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
#if __has_include("lvgl.h")
#include "lvgl.h"
#elif __has_include("lvgl/lvgl.h")
#include "lvgl/lvgl.h"
#else
#include "lvgl.h"
#endif
#else
#include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_events.h"
// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_Panel1;
extern lv_obj_t * ui_Panel2;
extern lv_obj_t * ui_Panel3;
extern lv_obj_t * ui_Panel4;
extern lv_obj_t * ui_Label2;
extern lv_obj_t * ui_Label3;
extern lv_obj_t * ui_Panel5;
extern lv_obj_t * ui_Panel6;
extern lv_obj_t * ui_Panel7;
extern lv_obj_t * ui_Label4;
extern lv_obj_t * ui_Label5;
extern lv_obj_t * ui_Label1;
extern lv_obj_t * ui_Label6;
extern lv_obj_t * ui_Label7;
extern lv_obj_t * ui_Panel8;
extern lv_obj_t * ui_Chart1;
extern lv_obj_t * ui_Image4;
extern lv_obj_t * ui_Label8;
extern lv_obj_t * ui_Label9;
extern lv_obj_t * ui_Label10;
extern lv_obj_t * ui_Image5;
extern lv_obj_t * ui_Label11;
extern lv_obj_t * ui_Label12;
extern lv_obj_t * ui_Spinner2;
extern lv_obj_t * ui_Label13;
extern lv_obj_t * ui_Bar1;
extern lv_obj_t * ui_Label14;
extern lv_obj_t * ui_Panel9;
extern lv_obj_t * ui_Label15;
extern lv_obj_t * ui_Label16;
extern lv_obj_t * ui_Label17;
extern lv_obj_t * ui____initial_actions0;

LV_IMG_DECLARE(ui_img_1894507902);    // assets\Custom-Icon-Design-Mono-General-4-Power.48.png
LV_IMG_DECLARE(ui_img_1215904128);    // assets\Dakirby309-Simply-Styled-YouTube.32.png
LV_IMG_DECLARE(ui_img_506958519);    // assets\Custom-Icon-Design-Mono-General-4-Power.32.png
LV_IMG_DECLARE(ui_img_268954820);    // assets\Custom-Icon-Design-Mono-General-4-Power.64.png

LV_FONT_DECLARE(ui_font_BIG);
LV_FONT_DECLARE(ui_font_MID);

void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
